/**
 * Report Types
 *
 * Type definitions for the report generation system.
 *
 * @module services/reports/types
 */

import type { Project, Vulnerability, Component } from '@@/types'

/**
 * Risk score information for a vulnerability
 */
export interface RiskScoreResult {
  score: number
  factors: {
    kev: number
    epss: number
    severity: number
  }
  breakdown: string
}

/**
 * Project statistics for reports
 */
export interface ReportStatistics {
  totalVulnerabilities: number
  criticalCount: number
  highCount: number
  mediumCount: number
  lowCount: number
  noneCount: number
  totalComponents: number
  vulnerableComponents: number
  kevCount: number
  avgEpssScore: number
}

/**
 * Options for report generation
 */
export interface ReportOptions {
  /** Report title */
  title: string
  /** Project name */
  projectName: string
  /** Include executive summary section */
  includeExecutiveSummary: boolean
  /** Include charts and visualizations */
  includeCharts: boolean
  /** Company logo (base64 or URL) */
  companyLogo?: string
  /** Company name for footer */
  companyName?: string
  /** Generated by line */
  generatedBy?: string
  /** Filter by date range */
  dateRange?: {
    start: Date
    end: Date
  }
  /** Minimum severity to include */
  minSeverity?: 'critical' | 'high' | 'medium' | 'low'
  /** Include remediation recommendations */
  includeRecommendations?: boolean
  /** Report theme */
  theme?: 'light' | 'dark'
}

/**
 * Data for report generation
 */
export interface ReportData {
  /** Project information */
  project: Project
  /** Vulnerability list */
  vulnerabilities: Vulnerability[]
  /** Component list */
  components: Component[]
  /** Statistics summary */
  statistics: ReportStatistics
  /** Risk scores by vulnerability ID */
  riskScores?: Map<string, RiskScoreResult>
}

/**
 * Generated report result
 */
export interface GeneratedReport {
  /** Report content (HTML or PDF blob) */
  content: string | Blob
  /** Content type */
  contentType: 'text/html' | 'application/pdf'
  /** Filename for download */
  filename: string
  /** Size in bytes */
  size: number
}

/**
 * Chart data for visualizations
 */
export interface ChartData {
  labels: string[]
  datasets: {
    label: string
    data: number[]
    backgroundColor?: string | string[]
    borderColor?: string | string[]
  }[]
}

/**
 * Executive summary metrics
 */
export interface ExecutiveSummaryMetrics {
  /** Total risk score (0-100) */
  overallRiskScore: number
  /** Risk level label */
  riskLevel: 'Critical' | 'High' | 'Medium' | 'Low'
  /** Trend compared to previous scan */
  trend: 'up' | 'down' | 'stable'
  /** Percentage change */
  trendPercentage?: number
  /** Key findings */
  keyFindings: string[]
  /** Top vulnerable components */
  topVulnerableComponents: Array<{
    name: string
    version: string
    vulnerabilityCount: number
    highestSeverity: string
  }>
  /** Recommended actions */
  recommendedActions: string[]
}
