export type WsEventType =
  | 'sync-progress'
  | 'sync-complete'
  | 'sync-error'
  | 'delta-sync-progress'
  | 'delta-sync-complete'
  | 'delta-sync-error'
  | 'bulk-download-progress'
  | 'scan-progress'
  | 'backup-created'
  | 'backup-restored'
  | 'backup-deleted'
  | 'backup-config-updated'
  | 'kev-synced'
